source "http://rubygems.org"

gem "i18n"
gem "sinatra"
gem "active_support"
gem "rake"
gem "gumdrop"

# Add your dependencies here:

# For template support:
# gem "less"
# gem "haml"
# gem "slim"
# gem "sass"
# gem "coffee-script"

# For JavaScript stitching and compressing:
# gem 'packr'
# gem 'uglifier'
# gem 'yui-compressor'
# gem 'jsmin'
# gem 'stitch-rb'
# gem 'sprockets'

# For markdown support, a couple of options:
# gem "redcarpet"
# gem "kramdown", :git => "git://github.com/darthapo/kramdown.git"
# gem "rdiscount"
# gem 'maruku'

# For xml generation support:
# gem 'builder'
