source "http://rubygems.org"

gem "sinatra"
gem "active_support"
gem "i18n"
gem "rake"
gem "gumdrop", :git=>"git://github.com/darthapo/gumdrop.git"

#
# Add your dependencies here:

gem "sass"
gem "haml"
gem "coffee-script"

# gem "rdiscount"
# gem "less"

