source "http://rubygems.org"

gem "sinatra"
gem "active_support"
gem "i18n"
gem "rake"
gem "gumdrop"

# Add your dependencies here:

gem "sass"
gem "coffee-script"

# gem "rdiscount"
# gem "less"
# gem "haml"

