source "http://rubygems.org"

gem "i18n"
gem "sinatra"
gem "active_support"
gem "rake"
gem "gumdrop"

# Add your dependencies here:

gem "sass"
gem "coffee-script"

# For markdown support, a couple of options:
# gem "rdiscount"
# gem 'maruku'

# For template support:
# gem "less"
# gem "haml"
# gem "slim"
# gem 'builder'
