source "http://rubygems.org"

# for the watch command
# gem "listen"

# Add your dependencies here:

# For template support:
# gem "less"
# gem "haml"
# gem "slim"
gem "erubis"
gem "sass"
gem "coffee-script"

# For JavaScript stitching and compressing:
#gem 'uglifier'
#gem 'yui-compressor'
#gem 'packr'
gem 'jsmin'
gem 'sprockets'
# gem 'stitch-rb'

# For markdown support, a couple of options:
gem "kramdown" #, :git => "git://github.com/darthapo/kramdown.git" #(github code-fence support)
# gem 'redcarpet'
# gem "rdiscount"
# gem 'maruku'

# For xml generation support:
gem 'builder'

gem 'json', '~> 1.7.7'
