require 'rubygems'
require "bundler/setup"
require 'gumdrop'

# For the SYNC task
USER='user'
SERVER='server.com'
FOLDER="~/#{SERVER}"

desc "Build source files into output_dir"
task :build do
  Gumdrop::CLI::Internal.new.build
end

desc "Run development server"
task :server do
  Gumdrop::CLI::Internal.new.server
end
task :serve => :server

desc "Outputs the Gumdrop version"
task :version do
  puts Gumdrop::VERSION
end

task :default do
  puts `rake -T`
end

desc "Syncs with public server using rsync (if configured)"
task :sync do
  site= Gumdrop::Site.new Gumdrop.fetch_site_file
  output= File.expand_path site.config.output_dir
  cmd= "rsync -avz --delete #{output} #{USER}@#{SERVER}:#{FOLDER}"
  puts "Running:\n#{cmd}\n"
  system(cmd)
  puts "Done."
end
