source "http://rubygems.org"

gem "i18n"
gem "sinatra"
gem "active_support"

gem "rake"
gem "gumdrop"

# Add your dependencies here:

# For template support:
# gem "less"
# gem "haml"
gem "slim"
gem "sass"
gem "coffee-script"

# For JavaScript stitching and compressing:
#gem 'uglifier'
#gem 'yui-compressor'
gem 'jsmin'
gem 'stitch-rb'

# For markdown support, a couple of options:
# gem "rdiscount"
# gem 'maruku'

# For xml generation support:
# gem 'builder'

