source "http://rubygems.org"

here= File.dirname(__FILE__)

gem "sinatra"
gem "active_support"
gem "i18n"
gem "rake"
gem "gumdrop", :path=>"#{here}/../../"

# Add your dependencies here:

gem "sass"
gem "coffee-script"

# gem "rdiscount"
# gem "less"
# gem "haml"

