source "http://rubygems.org"

here= File.dirname(__FILE__)

gem "i18n"
gem "sinatra"
gem "active_support"
gem "rake"
gem "gumdrop", :path=>"#{here}/../../"

# Add your dependencies here:

gem "sass"
gem "coffee-script"

# gem "rdiscount"
# gem "less"
# gem "haml"
gem "slim"

gem 'maruku'
gem 'builder'