require 'rubygems'
require "bundler/setup"
require 'gumdrop'

# For the SYNC task
USER='user'
SERVER='server.com'
FOLDER="~/#{SERVER}"


task :default  do
  sh 'rake -T'
end

desc "Build source files into output"
task :build do
  Gumdrop.run()
end


desc "Run development server"
task :serve do
  Gumdrop.config.auto_run= true
  Gumdrop::Server
end

desc "Syncs with public server using rsync (if configured)"
task :sync do
  cmd= "rsync -avz --delete output/ #{USER}@#{SERVER}:#{FOLDER}"
  puts "Running:\n#{cmd}\n"
  system(cmd)
  puts "Done."
end

desc "Outputs the Gumdrop version"
task :version do
  puts Gumdrop::VERSION
end

task :default do
  `rake -T`
end